name: py

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          - name: install
          run: |
            python -m pip install --upgrade pip
            pip install pytest-playwright beautifulsoup4
            playwright install
      - name: execute
        run: |
          python main.py
