name: Scraper

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup 
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 pytest-playwright
          playwright install
      - name: Scrape
        run: python src/main.py
